import VuiComponent from '../vuiComponent';
import { color, elevation, size } from '../constant';
declare type SizeStyles = {
    size?: size | string | number;
    height?: string | number;
    width?: string | number;
};
declare type SpaceSize = size | string | number | undefined;
declare type SpaceStyles = {
    margin?: string;
    marginX?: string;
    marginY?: string;
    marginTop?: string;
    marginBottom?: string;
    marginLeft?: string;
    marginRight?: string;
    padding?: string;
    paddingX?: string;
    paddingY?: string;
    paddingTop?: string;
    paddingBottom?: string;
    paddingLeft?: string;
    paddingRight?: string;
};
export default class BaseMixin extends VuiComponent {
    size?: size | string | number;
    height?: string | number;
    width?: string | number;
    fontColor: color | undefined;
    color: color | undefined;
    elevation: elevation | undefined;
    marginLeft: SpaceSize;
    marginRight: SpaceSize;
    marginTop: SpaceSize;
    marginBottom: SpaceSize;
    marginX: SpaceSize;
    marginY: SpaceSize;
    margin: SpaceSize;
    paddingLeft: SpaceSize;
    paddingRight: SpaceSize;
    paddingTop: SpaceSize;
    paddingBottom: SpaceSize;
    paddingX: SpaceSize;
    paddingY: SpaceSize;
    padding: SpaceSize;
    readonly sizeStyle: SizeStyles;
    readonly colorStyle: {};
    readonly elevationStyle: {};
    readonly spaceStyle: SpaceStyles;
    readonly baseStyle: {
        size?: string | number | undefined;
        height?: string | number | undefined;
        width?: string | number | undefined;
        margin?: string | undefined;
        marginX?: string | undefined;
        marginY?: string | undefined;
        marginTop?: string | undefined;
        marginBottom?: string | undefined;
        marginLeft?: string | undefined;
        marginRight?: string | undefined;
        padding?: string | undefined;
        paddingX?: string | undefined;
        paddingY?: string | undefined;
        paddingTop?: string | undefined;
        paddingBottom?: string | undefined;
        paddingLeft?: string | undefined;
        paddingRight?: string | undefined;
    };
}
export {};
