import { Vue } from 'vue-property-decorator';
import { Fill, size } from '../core/constants';
export default class MFrame extends Vue {
    name: string;
    transition?: boolean;
    fillHeader?: Fill;
    fillFooter?: Fill;
    headerSize?: size;
    headerIndex?: number;
    headerFloat?: boolean;
    footerSize?: size;
    footerIndex?: number;
    footerFloat?: boolean;
    leftSize?: size;
    leftIndex?: number;
    leftFloat?: boolean;
    rightSize?: size;
    rightIndex?: number;
    rightFloat?: boolean;
    private readonly classes;
    private readonly styles;
    private isHeader;
    private isFooter;
    private isLeft;
    private isRight;
    private RHeader;
    private RFooter;
    private RLeft;
    private RRight;
    private render;
}
