import { Vue } from 'vue-property-decorator';
import { Fill, size } from '../core/constant';
export default class MView extends Vue {
    fillHeader?: Fill;
    fillFooter?: Fill;
    headerSize?: size;
    headerIndex?: number;
    headerTransition?: boolean;
    footerSize?: size;
    footerIndex?: number;
    footerTransition?: boolean;
    leftSize?: size;
    leftIndex?: number;
    leftTransition?: boolean;
    rightSize?: size;
    rightIndex?: number;
    rightTransition?: boolean;
    private readonly classes;
    private readonly styles;
    private isHeader;
    private isFooter;
    private isLeft;
    private isRight;
    private RHeader;
    private RFooter;
    private RLeft;
    private RRight;
    private handlePartShow;
    private render;
}
