import mixBase from '../core/mixin/base';
import { typeHeader, typeHover, typeSelect } from './constant';
declare const MTable_base: import("vue-class-component/lib/declarations").VueClass<mixBase>;
export default class MTable extends MTable_base {
    name: string;
    border?: boolean;
    data: any[];
    keyField?: string;
    header?: typeHeader;
    hover?: typeHover;
    rowSelect?: boolean;
    select?: typeSelect;
    selected?: any;
    noSelect?: any;
    rowExpand?: boolean;
    expand?: typeSelect;
    expanded?: any;
    noExpand?: any;
    filter?: () => boolean;
    onExpand(row: any, index: number): void;
    onExpandAll(row: any, index: number): void;
    onSelect(row: any, index: number): void;
    onSelectAll(row: any, index: number): void;
    onRowClick(row: any, index: number): void;
    onRowDblclick(row: any, index: number): void;
    handleDataUpdate(val: any[]): void;
    handleSelectedUpdate(val: any): void;
    handleExpandedUpdate(val: any): void;
    syncSelected(data: any): void;
    syncExpanded(data: any): void;
    TableStore: any;
    readonly TableCols: any[];
    dataAdaptI(val?: any[]): any[];
    readonly styles: {
        size?: string | number | undefined;
        height?: string | number | undefined;
        width?: string | number | undefined;
        padding?: string | number | undefined;
        paddingX?: string | number | undefined;
        paddingY?: string | number | undefined;
        paddingTop?: string | number | undefined;
        paddingBottom?: string | number | undefined;
        paddingLeft?: string | number | undefined;
        paddingRight?: string | number | undefined;
        margin?: string | number | undefined;
        marginX?: string | number | undefined;
        marginY?: string | number | undefined;
        marginTop?: string | number | undefined;
        marginBottom?: string | number | undefined;
        marginLeft?: string | number | undefined;
        marginRight?: string | number | undefined;
    };
    readonly classes: {};
    render(): JSX.Element;
}
export {};
