import { Vue } from 'vue-property-decorator';
import { typeHeader, typeHover, typeSelect } from './constant';
export default class MTable extends Vue {
    name: string;
    bordered?: boolean;
    data: any[];
    keyField?: string;
    header?: typeHeader;
    hover?: typeHover;
    rowSelect?: boolean;
    select?: typeSelect;
    selected?: any;
    noSelect?: any;
    rowExpand?: boolean;
    expand?: typeSelect;
    expanded?: any;
    noExpand?: any;
    filter?: () => boolean;
    onExpand(row: any, index: number): void;
    onExpandAll(row: any, index: number): void;
    onSelect(row: any, index: number): void;
    onSelectAll(row: any, index: number): void;
    onRowClick(row: any, index: number): void;
    onRowDblclick(row: any, index: number): void;
    handleDataUpdate(val: any[]): void;
    handleSelectedUpdate(val: any): void;
    handleExpandedUpdate(val: any): void;
    syncSelected(data: any): void;
    syncExpanded(data: any): void;
    TableStore: any;
    readonly TableCols: any[];
    dataAdaptI(val?: any[]): any[];
    readonly styles: any;
    readonly classes: any;
    render(): JSX.Element;
}
