import mixBase from '../core/mixin/base';
import { dateValueFormat, datePickerType } from '../core/constant';
declare const MTimePicker_base: import("vue-class-component/lib/declarations").VueClass<mixBase>;
export default class MTimePicker extends MTimePicker_base {
    name: string;
    landscope: boolean;
    desync: boolean;
    value: any;
    valueFormat: dateValueFormat;
    ampm: boolean;
    hourStep: number;
    minuteStep: number;
    max: any;
    min: any;
    firstDayOfWeek: number;
    pickerType: datePickerType;
    confirmation: boolean;
    onConfirm(): void;
    onCancel(): void;
    onInput(val: any): void;
    readonly styles: {
        size?: string | number | undefined;
        height?: string | number | undefined;
        width?: string | number | undefined;
        padding?: string | number | undefined;
        paddingX?: string | number | undefined;
        paddingY?: string | number | undefined;
        paddingTop?: string | number | undefined;
        paddingBottom?: string | number | undefined;
        paddingLeft?: string | number | undefined;
        paddingRight?: string | number | undefined;
        margin?: string | number | undefined;
        marginX?: string | number | undefined;
        marginY?: string | number | undefined;
        marginTop?: string | number | undefined;
        marginBottom?: string | number | undefined;
        marginLeft?: string | number | undefined;
        marginRight?: string | number | undefined;
    };
    readonly classes: {
        'm--landscope': boolean;
    };
    valueAdaptI(val: any): number;
    valueAdaptO(val: number): any;
    onValueUpdate(val: any, oldVal: any): void;
    onAMPMUpdate(val: any, oldVal: any): void;
    onPickerTypeChange(val: any): void;
    DateStore: any;
    RPanel(): JSX.Element;
    RHandler(): JSX.Element | undefined;
    render(): JSX.Element;
}
export {};
